'use client';

export default function DiffViewer({ patch }) {
  const defaultDiff = `--- target_app/app.py (Original)
+++ target_app/app.py (Self-Healed)
@@ -12,6 +12,7 @@
 app = FastAPI(title="Canary Target")
+inventory_lock = asyncio.Lock()

@@ -42,8 +43,9 @@
 async def reserve_stock(req: ReservationRequest):
-    # Intentional race condition: no lock between read and write
-    current_stock = db["items"][req.item_id]["stock"]
-    if current_stock >= req.quantity:
-        await asyncio.sleep(0.05)  # Simulate DB latency window
-        db["items"][req.item_id]["stock"] = current_stock - req.quantity
-        return {"status": "reserved", "remaining": db["items"][req.item_id]["stock"]}
+    async with inventory_lock:
+        current_stock = db["items"][req.item_id]["stock"]
+        if current_stock < req.quantity:
+            raise HTTPException(status_code=409, detail="Insufficient stock")
+        db["items"][req.item_id]["stock"] -= req.quantity
+        return {"status": "reserved", "remaining": db["items"][req.item_id]["stock"]}`;

  const currentPatch = patch || {
    targetFile: 'target_app/app.py',
    explanation: 'Introduced an asyncio.Lock() mutex around the check-and-decrement sequence in reserve_stock to eliminate the time-of-check to time-of-use (TOCTOU) race condition.',
    antiLazyScore: 100,
    model: 'deepseek-ai/DeepSeek-R1 (Nebius Token-Factory)',
    ttftMs: 240,
    diff: defaultDiff,
  };

  const lines = (currentPatch.diff || defaultDiff).split('\n');

  return (
    <div className="diff-viewer-card">
      {/* Diff Header */}
      <div className="diff-header">
        <div className="diff-title-box">
          <span className="diff-file-icon">📄</span>
          <div>
            <div className="diff-filename font-mono">{currentPatch.targetFile}</div>
            <div className="diff-meta">Generated by {currentPatch.model}</div>
          </div>
        </div>

        <div className="diff-badges">
          <div className="badge badge-success">
            <span>🛡️ Anti-Lazy AST:</span>
            <span className="font-mono">VALIDATED (0 pass/no-op)</span>
          </div>
          <div className="badge badge-purple">
            <span>TTFT:</span>
            <span className="font-mono">{currentPatch.ttftMs || 240}ms</span>
          </div>
        </div>
      </div>

      {/* Explanation Banner */}
      {currentPatch.explanation && (
        <div className="explanation-banner">
          <span className="explanation-icon">💡</span>
          <p className="explanation-text">{currentPatch.explanation}</p>
        </div>
      )}

      {/* Code Window */}
      <div className="code-window">
        <div className="code-topbar">
          <span className="dot dot-red" />
          <span className="dot dot-yellow" />
          <span className="dot dot-green" />
          <span className="window-title font-mono">unified-diff.patch</span>
        </div>

        <pre className="diff-content font-mono">
          {lines.map((line, idx) => {
            let lineClass = 'line-context';
            if (line.startsWith('+') && !line.startsWith('+++')) {
              lineClass = 'line-added';
            } else if (line.startsWith('-') && !line.startsWith('---')) {
              lineClass = 'line-removed';
            } else if (line.startsWith('@@')) {
              lineClass = 'line-chunk';
            }

            return (
              <div key={idx} className={`diff-line ${lineClass}`}>
                <span className="line-num">{idx + 1}</span>
                <span className="line-text">{line}</span>
              </div>
            );
          })}
        </pre>
      </div>

      <style jsx>{`
        .diff-viewer-card {
          background: rgba(255, 255, 255, 0.03);
          border: 1px solid rgba(255, 255, 255, 0.07);
          border-radius: 12px;
          padding: 20px;
          display: flex;
          flex-direction: column;
          gap: 14px;
        }

        .diff-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          flex-wrap: wrap;
          gap: 12px;
        }

        .diff-title-box {
          display: flex;
          align-items: center;
          gap: 10px;
        }

        .diff-file-icon {
          font-size: 20px;
        }

        .diff-filename {
          font-size: 14px;
          font-weight: 700;
          color: #ffffff;
        }

        .diff-meta {
          font-size: 11px;
          color: #8b949e;
        }

        .diff-badges {
          display: flex;
          align-items: center;
          gap: 8px;
        }

        .badge-purple {
          background: rgba(168, 85, 247, 0.12);
          border: 1px solid rgba(168, 85, 247, 0.3);
          color: #c084fc;
          font-size: 11px;
          padding: 4px 10px;
          border-radius: 6px;
          display: flex;
          gap: 6px;
        }

        .explanation-banner {
          display: flex;
          align-items: flex-start;
          gap: 10px;
          background: rgba(0, 212, 255, 0.05);
          border: 1px solid rgba(0, 212, 255, 0.2);
          border-radius: 8px;
          padding: 10px 14px;
        }

        .explanation-icon {
          font-size: 16px;
        }

        .explanation-text {
          font-size: 12px;
          color: #c9d1d9;
          line-height: 1.5;
          margin: 0;
        }

        .code-window {
          background: #06090e;
          border: 1px solid rgba(255, 255, 255, 0.08);
          border-radius: 8px;
          overflow: hidden;
        }

        .code-topbar {
          background: #0d1117;
          border-bottom: 1px solid rgba(255, 255, 255, 0.06);
          padding: 8px 14px;
          display: flex;
          align-items: center;
          gap: 8px;
        }

        .dot {
          width: 10px;
          height: 10px;
          border-radius: 50%;
        }

        .dot-red { background: #ff5f56; }
        .dot-yellow { background: #ffbd2e; }
        .dot-green { background: #27c93f; }

        .window-title {
          font-size: 11px;
          color: #6e7681;
          margin-left: 8px;
        }

        .diff-content {
          padding: 12px 0;
          margin: 0;
          font-size: 12px;
          line-height: 1.5;
          overflow-x: auto;
        }

        .diff-line {
          display: flex;
          padding: 1px 12px;
          gap: 14px;
        }

        .line-num {
          color: #484f58;
          width: 28px;
          text-align: right;
          user-select: none;
        }

        .line-text {
          flex: 1;
        }

        .line-added {
          background: rgba(46, 213, 115, 0.15);
          color: #2ed573;
          border-left: 3px solid #2ed573;
        }

        .line-removed {
          background: rgba(255, 71, 87, 0.15);
          color: #ff4757;
          border-left: 3px solid #ff4757;
        }

        .line-chunk {
          color: #00d4ff;
          background: rgba(0, 212, 255, 0.06);
        }

        .line-context {
          color: #c9d1d9;
        }
      `}</style>
    </div>
  );
}
