'use client';

import { useState } from 'react';

export default function DiffViewer({ patch }) {
  const [copied, setCopied] = useState(false);

  const defaultDiff = `--- target_app/app.py (Original)
+++ target_app/app.py (Self-Healed)
@@ -12,6 +12,7 @@
 app = FastAPI(title="Canary Target")
+inventory_lock = asyncio.Lock()

@@ -42,8 +43,9 @@
 async def reserve_stock(req: ReservationRequest):
-    # Intentional race condition: no lock between read and write
-    current_stock = db["items"][req.item_id]["stock"]
-    if current_stock >= req.quantity:
-        await asyncio.sleep(0.05)  # Simulate DB latency window
-        db["items"][req.item_id]["stock"] = current_stock - req.quantity
-        return {"status": "reserved", "remaining": db["items"][req.item_id]["stock"]}
+    async with inventory_lock:
+        current_stock = db["items"][req.item_id]["stock"]
+        if current_stock < req.quantity:
+            raise HTTPException(status_code=409, detail="Insufficient stock")
+        db["items"][req.item_id]["stock"] -= req.quantity
+        return {"status": "reserved", "remaining": db["items"][req.item_id]["stock"]}`;

  const currentPatch = patch || {
    targetFile: 'target_app/app.py',
    explanation: 'Introduced an asyncio.Lock() mutex around the check-and-decrement sequence in reserve_stock to eliminate the time-of-check to time-of-use (TOCTOU) race condition.',
    antiLazyScore: 100,
    model: 'deepseek-ai/DeepSeek-R1 (Nebius Token-Factory)',
    ttftMs: 240,
    diff: defaultDiff,
  };

  const lines = (currentPatch.diff || defaultDiff).split('\n');

  const handleCopyDiff = () => {
    navigator.clipboard?.writeText(currentPatch.diff || defaultDiff);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="diff-viewer-card">
      {/* Header */}
      <div className="diff-header">
        <div className="diff-title-box">
          <span className="diff-file-icon">📄</span>
          <div>
            <div className="diff-filename font-mono">{currentPatch.targetFile}</div>
            <div className="diff-meta">Generated by {currentPatch.model}</div>
          </div>
        </div>

        <div className="diff-badges">
          <div className="badge badge-success font-mono">
            <span>🛡️ AST MUTEX:</span>
            <span>VALIDATED</span>
          </div>
          <div className="badge badge-purple font-mono">
            <span>TTFT:</span>
            <span>{currentPatch.ttftMs || 240}ms</span>
          </div>
          <button onClick={handleCopyDiff} className="copy-btn font-mono">
            {copied ? '✔ Copied' : 'Copy Patch'}
          </button>
        </div>
      </div>

      {/* Rationale Banner */}
      <div className="explanation-banner">
        <div className="expl-tag font-mono">NEBIUS REASONING RATIONALE</div>
        <p className="expl-text">{currentPatch.explanation}</p>
      </div>

      {/* Code Diff Box */}
      <div className="diff-box font-mono">
        {lines.map((line, idx) => {
          let lineType = 'normal';
          if (line.startsWith('+') && !line.startsWith('+++')) lineType = 'add';
          else if (line.startsWith('-') && !line.startsWith('---')) lineType = 'del';
          else if (line.startsWith('@@')) lineType = 'chunk';

          return (
            <div key={idx} className={`diff-line diff-${lineType}`}>
              <span className="line-num">{idx + 1}</span>
              <span className="line-symbol">
                {lineType === 'add' ? '+' : lineType === 'del' ? '-' : ' '}
              </span>
              <span className="line-content">
                {lineType === 'add' || lineType === 'del' ? line.slice(1) : line}
              </span>
            </div>
          );
        })}
      </div>

      <style jsx>{`
        .diff-viewer-card {
          background: linear-gradient(180deg, rgba(14, 21, 36, 0.9) 0%, rgba(10, 16, 28, 0.95) 100%);
          border: 1px solid var(--border-default);
          border-radius: var(--radius-lg);
          padding: 20px;
          display: flex;
          flex-direction: column;
          gap: 16px;
          box-shadow: var(--shadow-card);
          backdrop-filter: blur(16px);
        }

        .diff-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          gap: 12px;
          flex-wrap: wrap;
        }

        .diff-title-box {
          display: flex;
          align-items: center;
          gap: 10px;
        }

        .diff-file-icon {
          font-size: 20px;
        }

        .diff-filename {
          font-size: 13.5px;
          font-weight: 700;
          color: var(--text-primary);
        }

        .diff-meta {
          font-size: 11px;
          color: var(--text-muted);
        }

        .diff-badges {
          display: flex;
          align-items: center;
          gap: 8px;
        }

        .copy-btn {
          background: rgba(255, 255, 255, 0.05);
          border: 1px solid var(--border-default);
          color: var(--text-secondary);
          padding: 4px 10px;
          border-radius: var(--radius-xs);
          font-size: 11px;
          font-weight: 600;
          cursor: pointer;
          transition: all var(--transition-fast);
        }

        .copy-btn:hover {
          background: rgba(255, 255, 255, 0.1);
          color: var(--text-primary);
        }

        .explanation-banner {
          background: rgba(56, 189, 248, 0.06);
          border: 1px solid rgba(56, 189, 248, 0.2);
          border-radius: var(--radius-md);
          padding: 12px 16px;
          display: flex;
          flex-direction: column;
          gap: 4px;
        }

        .expl-tag {
          font-size: 10px;
          font-weight: 700;
          color: var(--accent-cyan);
          letter-spacing: 0.1em;
        }

        .expl-text {
          font-size: 12px;
          color: var(--text-primary);
          line-height: 1.5;
        }

        .diff-box {
          background: #05080e;
          border: 1px solid var(--border-default);
          border-radius: var(--radius-md);
          overflow-x: auto;
          font-size: 11.5px;
          line-height: 1.6;
        }

        .diff-line {
          display: flex;
          padding: 2px 10px;
        }

        .line-num {
          width: 32px;
          color: var(--text-faint);
          user-select: none;
          font-size: 10.5px;
          text-align: right;
          padding-right: 12px;
        }

        .line-symbol {
          width: 14px;
          font-weight: 700;
          user-select: none;
        }

        .line-content {
          flex: 1;
          white-space: pre;
        }

        .diff-normal {
          color: var(--text-secondary);
        }

        .diff-add {
          background: rgba(16, 185, 129, 0.12);
          color: #6ee7b7;
        }

        .diff-add .line-symbol {
          color: #34d399;
        }

        .diff-del {
          background: rgba(244, 63, 94, 0.12);
          color: #fca5a5;
        }

        .diff-del .line-symbol {
          color: #f87171;
        }

        .diff-chunk {
          background: rgba(99, 102, 241, 0.1);
          color: #a5b4fc;
          font-weight: 600;
        }
      `}</style>
    </div>
  );
}
